Repository twbs/bootstrap, pull requests merged in 2022-11, with the labels that each got.

#37425 Fix deprecation warning with sass 1.56.0
  scss/_functions.scss
Labels: css, v5

#36027 Move `getElementFromSelector` & `getSelectorFromElement`
  js/src/carousel.js
  js/src/collapse.js
  js/src/dom/selector-engine.js
  js/src/modal.js
  js/src/offcanvas.js
  js/src/tab.js
  js/src/util/component-functions.js
  js/src/util/index.js
  js/tests/unit/dom/selector-engine.spec.js
  js/tests/unit/util/index.spec.js
Labels: js, v5, refactoring

#35566 Properly escape IDs in getSelector() to handle weird IDs (#35565)
  .bundlewatch.config.json
  js/src/dom/selector-engine.js
  js/src/util/index.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/tab.spec.js
Labels: js, v5, release-highlight

#37438 ref: refactor `getSelector` not to be exported
  js/src/dom/selector-engine.js
Labels: js, refactoring

#37439 Realign Bundlewatch values
  .bundlewatch.config.json
Labels: build, v5

#37378 Backport: NuGet Changes
  nuget/MyGet.ps1
  nuget/bootstrap.nuspec
  nuget/bootstrap.sass.nuspec
Labels: build, v4

#37459 CI: remove git credentials after checkout
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/calibreapp-image-actions.yml
  .github/workflows/codeql.yml
  .github/workflows/cspell.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
Labels: CI

#37471 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: v5, dependencies

#37473 fix: change `replaceAll` usage introduced in #35566
  js/src/util/index.js
Labels: js, v5

#37483 hydrateObj: use default param
  js/src/dom/event-handler.js
Labels: js, v5, refactoring

#37484 ESLint: enable prefer-template rule
  .eslintrc.json
  build/build-plugins.js
  js/src/util/index.js
  js/tests/karma.conf.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/tab.spec.js
  js/tests/unit/util/config.spec.js
  js/tests/visual/carousel.html
  js/tests/visual/modal.html
Labels: js, v5

#37485 Update site/.eslintrc.json
  site/.eslintrc.json
Labels: build, v5

#37481 Update CodeQL workflow
  .github/workflows/codeql.yml
Labels: CI

#37432 Docs: use `<button>` for dropdown/popover examples, explain preference over `<a>` for dropdowns, tweak collapse prose
  js/tests/unit/collapse.spec.js
  site/content/docs/5.2/components/collapse.md
  site/content/docs/5.2/components/dropdowns.md
  site/content/docs/5.2/components/modal.md
Labels: docs, accessibility, v5

#37482 Use `Object.entries` in more places
  js/src/dom/event-handler.js
  js/src/tooltip.js
  js/src/util/config.js
Labels: js, v5, refactoring

#37461 CI: switch to Node.js 18 LTS
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
Labels: CI

#37491 Make added-in badge page-level for z-index utilities
  site/content/docs/5.2/utilities/z-index.md
Labels: docs, v5

#37486 CodeQL: ignore dist folder
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: v5, CI

#37492 Docs: add margin between buttons in tooltip examples
  site/assets/scss/_component-examples.scss
Labels: docs, v5

#37406 Update input-group.md with form text example
  site/content/docs/5.2/forms/input-group.md
Labels: docs, v5

#37413 Grid Gap Updates
  .bundlewatch.config.json
  scss/_utilities.scss
  site/content/docs/5.2/utilities/spacing.md
Labels: css, v5

#37498 Fix accessibility of examples buttons
  site/layouts/shortcodes/example.html
Labels: docs, accessibility, v5

#37526 Fix var `--bs-body-font-family`. Keep quotes in the font stack.
  scss/_root.scss
Labels: css, v5

#37535 Docs: Fix Thirteenth typo on Navbars example
  site/content/docs/5.2/examples/navbars/index.html
Labels: docs, v5

#37538 Docs: Add black text/background examples
  site/content/docs/5.2/utilities/background.md
  site/content/docs/5.2/utilities/colors.md
Labels: docs, v5, color mode

#36831 Rework progress bar markup and styles
  scss/_progress.scss
  site/content/docs/5.2/components/progress.md
  site/content/docs/5.2/examples/cheatsheet-rtl/index.html
  site/content/docs/5.2/examples/cheatsheet/index.html
  site/content/docs/5.2/migration.md
  site/content/docs/5.2/utilities/position.md
Labels: docs, css, accessibility

#37354 Docs: rewrite/reorganise carousel docs page
  .cspell.json
  site/assets/js/snippets.js
  site/content/docs/5.2/components/carousel.md
Labels: docs, accessibility, v5

#37553 Docs: fix 'Usage > Enable dark mode' code example
  site/content/docs/5.2/customize/color-modes.md
Labels: docs, v5, color mode

#37568 Remove title from 'check2' icon SVG
  site/layouts/partials/icons.html
Labels: docs, v5
