Repository twbs/bootstrap, pull requests merged in 2022-01, with the labels that each got.

#35633 Tweak toast docs
  site/content/docs/4.6/components/toasts.md
Labels: docs, v4

#35639 Bump copyright year to 2022
  LICENSE
  README.md
  build/build-plugins.js
  build/change-version.js
  build/generate-sri.js
  build/vnu-jar.js
  build/zip-examples.js
  nuget/bootstrap.nuspec
  nuget/bootstrap.sass.nuspec
  scss/bootstrap-grid.scss
  scss/bootstrap-reboot.scss
  scss/bootstrap-utilities.scss
  scss/bootstrap.scss
  site/assets/js/application.js
  site/assets/scss/docs.scss
Labels: v4, v5, backport-to-v4

#35640 Update devDependencies
  package-lock.json
  package.json
Labels: v5, dependencies

#35641 Update nuget/bootstrap.png
  nuget/bootstrap.png
Labels: meta, v5

#35621 Fix offcanvas title in 'Enable body scrolling' example
  site/content/docs/5.1/components/offcanvas.md
Labels: docs

#35589 Remove explicit use of aria-hidden for offcanvas when closed
  js/src/offcanvas.js
  js/tests/unit/offcanvas.spec.js
  scss/_offcanvas.scss
Labels: js, accessibility, v5

#35609 Fix custom-checkbox and custom-radio in migration doc
  site/content/docs/5.1/migration.md
Labels: docs

#35656 fixed button text
  site/content/docs/5.1/components/list-group.md
Labels: docs, v5, skip-changelog

#35678 Update devDependencies
  config.yml
  package-lock.json
  package.json
Labels: v5, dependencies

#35647 Update cspell config
  .cspell.json
  package.json
  site/content/docs/5.1/components/modal.md
  site/content/docs/5.1/customize/sass.md
  site/content/docs/5.1/getting-started/rtl.md
  site/content/docs/5.1/migration.md
Labels: docs, meta, v5

#35682 fix isVisible behavior with new chrome version
  js/src/util/index.js
  js/tests/unit/util/index.spec.js
Labels: js, browser bug, v5, p2

#35586 build-plugins.js: use globby package
  build/build-plugins.js
  package-lock.json
  package.json
Labels: build, v5

#35683 README.md: mention Netlify
  README.md
Labels: meta, v5, skip-changelog

#35686 Update devDependencies
  package-lock.json
  package.json
Labels: v5, dependencies

#35649 Docs: group together reusable CSS for examples in a single stylesheet
  site/content/docs/5.1/examples/dropdowns/dropdowns.css
  site/content/docs/5.1/examples/features/features.css
  site/content/docs/5.1/examples/footers/footers.css
  site/content/docs/5.1/examples/footers/index.html
  site/content/docs/5.1/examples/headers/headers.css
  site/content/docs/5.1/examples/heroes/heroes.css
  site/content/docs/5.1/examples/list-groups/list-groups.css
  site/content/docs/5.1/examples/modals/modals.css
  site/content/docs/5.1/examples/sidebars/index.html
  site/content/docs/5.1/examples/sidebars/sidebars.css
  site/layouts/_default/examples.html
Labels: docs, css, v5

#35712 Update devDependencies
  package-lock.json
  package.json
Labels: v5, dependencies

#35704 Fix spelling mistake in footer example
  site/content/docs/5.1/examples/footers/index.html
Labels: examples

#35696 Docs - Remove duplicate Octicons entry in icons list
  site/data/icons.yml
Labels: docs

#35741 docs: remove moot `autocomplete` attributes
  site/content/docs/5.1/components/buttons.md
Labels: docs, v5

#35733 docs: fix a couple typos found with codespell
  site/content/docs/5.1/examples/blog/index.html
  site/content/docs/5.1/examples/cheatsheet-rtl/index.html
Labels: examples, v5

#35573 Move linkinator to GitHub Actions.
  .github/workflows/docs.yml
  package-lock.json
  package.json
Labels: build, v4, v5, backport-to-v4, CI

#35659 tests: replace 'done' callback with 'Promise' to fix deprecation errors
  js/tests/README.md
  js/tests/unit/alert.spec.js
  js/tests/unit/carousel.spec.js
  js/tests/unit/collapse.spec.js
  js/tests/unit/dom/event-handler.spec.js
  js/tests/unit/dom/manipulator.spec.js
  js/tests/unit/dropdown.spec.js
  js/tests/unit/jquery.spec.js
  js/tests/unit/modal.spec.js
  js/tests/unit/offcanvas.spec.js
  js/tests/unit/popover.spec.js
  js/tests/unit/scrollspy.spec.js
  js/tests/unit/tab.spec.js
  js/tests/unit/toast.spec.js
  js/tests/unit/tooltip.spec.js
  js/tests/unit/util/backdrop.spec.js
  js/tests/unit/util/focustrap.spec.js
  js/tests/unit/util/index.spec.js
  js/tests/unit/util/scrollbar.spec.js
  js/tests/unit/util/swipe.spec.js
Labels: tests, p2

#35680 Update cspell config
  .cspell.json
Labels: v5

#35585 Fix visual tests
  js/tests/visual/alert.html
  js/tests/visual/button.html
  js/tests/visual/carousel.html
  js/tests/visual/collapse.html
  js/tests/visual/dropdown.html
  js/tests/visual/modal.html
  js/tests/visual/popover.html
  js/tests/visual/scrollspy.html
  js/tests/visual/tab.html
  js/tests/visual/toast.html
  js/tests/visual/tooltip.html
Labels: v5, tests, affects-main-branch

#35684 Selector Engine: improve `parents` method to utilize newer JS native methods
  js/src/dom/selector-engine.js
Labels: js, v5, refactoring

#35593 Move cspell to Actions
  .github/workflows/cspell.yml
  package-lock.json
  package.json
Labels: build, v5, CI

#35546 More tooltip refactoring
  js/src/tooltip.js
Labels: js, v5, refactoring

#35735 Change X to Extra
  site/content/docs/5.1/layout/breakpoints.md
Labels: docs
