Repository twbs/bootstrap, pull requests merged in 2025-07, with the labels that each got.

#41585 Fix `color-contrast()` function for WCAG 2.1 compliance
  scss/_functions.scss
  scss/tests/mixins/_color-contrast.test.scss
Labels: css, accessibility, v5

#41571 OSSF Scorecard
  .github/workflows/scorecard.yml
  README.md
Labels: meta

#41595 Workflows: Use SHA-1 for third-party actions
  .github/workflows/browserstack.yml
  .github/workflows/bundlewatch.yml
  .github/workflows/calibreapp-image-actions.yml
  .github/workflows/codeql.yml
  .github/workflows/cspell.yml
  .github/workflows/css.yml
  .github/workflows/docs.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/node-sass.yml
  .github/workflows/release-notes.yml
  .github/workflows/scorecard.yml
Labels: build, github-actions, github_actions

#41609 Build(deps-dev): Bump the development-dependencies group with 2 updates
  package-lock.json
  package.json
Labels: v5, dependencies

#41621 Build(deps-dev): Bump the development-dependencies group with 4 updates
  package-lock.json
  package.json
Labels: v5, dependencies
