Repository twbs/bootstrap, pull requests merged in 2025-05, with the labels that each got.

#41425 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: v5, dependencies

#41286 Prevent .visually-hidden overflowing children to become focusable
  scss/mixins/_visually-hidden.scss
Labels: css, accessibility, v5

#41435 Add docs release prep script
  build/docs-prep.sh
Labels: docs, meta

#41440 Fix broken `View on GitHub` url
  site/src/layouts/DocsLayout.astro
Labels: docs, v5

#41443 Update `devDependencies`
  package-lock.json
  package.json
Labels: v5, dependencies

#41445 Update `devDependencies`
  package-lock.json
  package.json
Labels: v5, dependencies

#41456 Drop unused `@types/google.analytics` dev dependency and bump `@types` dev dependencies
  package-lock.json
  package.json
Labels: v5, dependencies

#41461 Realign `package.json` dev deps versions from `package-lock.json`
  package-lock.json
  package.json
Labels: v5, dependencies

#41464 Update `devDependencies`
  package-lock.json
  package.json
Labels: v5, dependencies

#41468 Fix HTML `<head>` content built from 'Download examples' button
  build/zip-examples.mjs
Labels: docs, v5

#41469 Consolidate multiple 'none' values in `box-shadow` Sass mixin
  scss/mixins/_box-shadow.scss
  scss/tests/mixins/_box-shadow.test.scss
Labels: css, v5

#41434 Refine sanitizer documentation
  site/src/content/docs/components/popovers.mdx
  site/src/content/docs/components/tooltips.mdx
  site/src/content/docs/getting-started/javascript.mdx
  site/src/scss/_content.scss
Labels: docs, v5, squash

#41482 Docs: ensure `stackblitz.js` loads conditionally as intended
  site/src/components/DocsScripts.astro
  site/src/components/Scripts.astro
Labels: docs, v5

#41483 Docs: Nav better a11y
  site/src/layouts/DocsLayout.astro
Labels: docs, accessibility, v5

#41486 Docs: fix typo on Masonry example
  site/src/assets/examples/masonry/index.astro
Labels: docs, v5

#41498 Add VS Code Extensions & Settings Configs
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: build, enhancement

#41492 Add section to Download page for IntelliSense extension
  site/src/content/docs/getting-started/download.mdx
  site/static/docs/[version]/assets/img/bootstrap-intellisense-autocomplete.png
Labels: docs, v5
