Repository twbs/bootstrap, pull requests merged in 2025-02, with the labels that each got.

#41150 Update fixtureId to FIXTURE_ID for consistency
  js/tests/helpers/fixture.js
Labels: js, v5, enhancement

#40917 Fix: clipboard icon not showing after multiple press
  site/assets/js/partials/code-examples.js
Labels: docs, v5

#38411 Add note about cancelling modal events to modal.md
  site/content/docs/5.3/components/modal.md
Labels: docs, js, v5

#41228 Docs: Simplify ids for checks, radios and switches
  site/content/docs/5.3/examples/cheatsheet-rtl/index.html
  site/content/docs/5.3/examples/cheatsheet/index.html
  site/content/docs/5.3/examples/sign-in/index.html
  site/content/docs/5.3/forms/checks-radios.md
Labels: docs, v5, enhancement

#41237 fix(examples): access to the examples page by removing duplicate `indexPath`
  site/data/examples.yml
Labels: v6
